# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c80d9e88da07de405360a89b328b8f3186d28d56098a1dc4511b7921da113d176a5cb67cf67145f47af4b952ff3a8cd6e66b9119629ae1cc3d200e7c038fe5

test:
  secret_key_base: b4dcb4e6399ae86528d160592327d2b1a07c6d5a0f5b0eb6b7d5bf68ee5c34715a6ac0ac6b5b9d03780512dd0e218c8900e26b8887bae548fcf42ea3090b6462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
